### ISSUE TITLE
Can't scan for iBeacon

### ISSUE THREAD

**Issue by hhseine** [RadiusNetworks/scanbeacon-gem#33]
I have a bunch of iBeacon in a room but when I run my script I don't see any one of them. I had a look at the gem and commented lines 76-78, now it works but I still get an exception sometimes.

**Comment by cupakromer** [comment]
Thanks for reporting this. We'd like to get to the bottom of what is happening but need some more information about the issue you are facing:

- What exception do you get?
- Which file did you comment out lines 76 - 78?
- What OS are you running on? Please include the version
- What is your Ruby version?

**Comment by hhseine** [comment]
Hey, 
I'am running Linaro (Debian 8.6) on a Dragonboard, I commented lines 76-78 in the file beacon_parser.rb. The ruby version is 2.1.5 and is the latest one I can use on this OS. About the exception, it comes from the file 'field.rb'. After commenting those lines it seems that the data is sometimes equal null, so without handling this I get this : " /var/lib/gems/2.1.0/gems/scan_beacon-0.7.11/lib/scan_beacon/beacon/field.rb:40:in `value': undefined method `size' for nil:NilClass (NoMethodError) "

**Comment by cupakromer** [comment]
I tested things with the latest release and iBeacon scanning works. One thing to note is that by default this library only scans for open source advertisement types. [Currently this includes](https://github.com/RadiusNetworks/scanbeacon-gem/blob/v0.7.11/lib/scan_beacon/beacon_parser.rb#L3-L9):

- AltBeacon
- Eddystone-UID
- Eddystone-URL
- Eddystone-TLM
- Eddystone-EID

As iBeacon is a proprietary format it's not included in this lib as a default. You can still use this lib to scan for any beacon type. You'll just need to [add a custom parser](https://github.com/RadiusNetworks/scanbeacon-gem#add-a-custom-beacon-layout) for whatever format you wish to scan. The parser string definition structure is based off of the [Android Beacon Library](https://github.com/altbeacon/android-beacon-library) format. A [search online](https://duckduckgo.com/?q=android+beacon+library+ibeacon+parser+format&t=h_&ia=qa) yields some helpful results.
